"""First Commit**

Revision ID: 5eba7a8fa16c
Revises: 
Create Date: 2026-09-04 16:08:52.078543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eba7a8fa16c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=False),
    sa.Column('banners', sa.JSON(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('rarity', sa.Enum('common', 'notcommon', 'grand', name='characterrarity'), nullable=False),
    sa.Column('chance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=False),
    sa.Column('rarity', sa.Enum('common', 'rare', 'epic', 'legendary', 'limited', name='itemrarity'), nullable=False),
    sa.Column('chance', sa.Float(), nullable=False),
    sa.Column('limit', sa.Integer(), server_default='1', nullable=False),
    sa.Column('purchase_text', sa.Text(), nullable=False),
    sa.Column('purchase_quantity', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.Column('quartz', sa.Float(), nullable=False),
    sa.Column('negative_quartz', sa.Float(), nullable=False),
    sa.Column('gold_quartz', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characterslots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'index', name='uq_user_slot_index')
    )
    op.create_table('inventoryslots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_rent', sa.Boolean(), nullable=False),
    sa.Column('rent', sa.Float(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventoryslots')
    op.drop_table('characterslots')
    op.drop_table('users')
    op.drop_table('items')
    op.drop_table('characters')
    # ### end Alembic commands ###
